Tests/birthday list
social-network-ya-practicum/backend pull request #46
Opened 2023-06-20 14:28 UTC by borrrv

2023-06-20 19:52 UTC, AndreyVnk approved these changes

2023-06-22 05:56 UTC, Imwisagist requested changes

2023-06-22 05:56 UTC, Imwisagist commented on api/serializers.py
А почему ты импорты из локальных файлов поставил между импортами из других пакетов? Мне кажется они стояли правильно.

2023-06-22 06:43 UTC, borrrv commented on api/serializers.py
Да, все верно, isort что-то намудрил

2023-06-22 06:59 UTC, Imwisagist approved these changes

2023-06-22 07:42 UTC, merged