Fix/error and security
social-network-ya-practicum/backend pull request #55
Opened 2023-06-23 14:07 UTC by borrrv

Добавил русификацию дней рождений, добавил переменные в env, ошибки обрабатываются одинаково теперь, добавил в Action новые переменные, workflow тоже обновил

2023-06-23 15:56 UTC, lllleeenna approved these changes

2023-06-23 19:26 UTC, Imwisagist requested changes
Если я апрувну твои коррективы, новый билд бекенда будет подключаться к новой базе в которой ничего нет, я не думаю что это понравится остальным людям которые создавали пользователей, посты, заполняли профили, давай всё-таки будем коннектиться к имеющейся БД

2023-06-24 18:20 UTC, borrrv commented
А, я этот момент и не заметил, переделаю

2023-06-25 10:35 UTC, Imwisagist approved these changes

2023-06-25 10:36 UTC, merged